name: micro-ROS HIL agent

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron: '00 4 * * *'

jobs:
  micro_ros_renesas_testbench:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distribution: humble
            branch: humble
            board_id: 19
          - ros_distribution: iron
            branch: iron
            board_id: 20
          - ros_distribution: rolling
            branch: main
            board_id: 21
    runs-on: rpi-ros2-${{ matrix.ros_distribution }}-${{ matrix.board_id }}
    steps:
    - uses: actions/checkout@v3
      with:
        path: ros_ws/src/micro_ros_renesas_testbench
        submodules: recursive
        ref: ${{ matrix.branch }}
    - name: Download dependencies
      run: |
        cd ros_ws
        rm -rf src/Micro-XRCE-DDS-Agent
        rm -rf src/micro-ROS-Agent
        rm -rf src/micro_ros_msgs
        vcs import --force --shallow --input src/micro_ros_renesas_testbench/requirements.repos src
    - name: Build micro-ROS agent
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.sh
        cd ros_ws
        colcon build --cmake-clean-cache --cmake-force-configure --packages-up-to microxrcedds_agent
        source install/local_setup.bash
        colcon build --packages-up-to micro_ros_agent --cmake-args -DMICROROSAGENT_SUPERBUILD=OFF