name: micro-ROS HIL tests

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron: '00 6 * * *'

jobs:
  micro_ros_renesas_testbench:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- ros_distribution: foxy
          #  branch: foxy
          #  board_id: 20
          - ros_distribution: galactic
            branch: feature/multiboard
            board_id: 19
          - ros_distribution: galactic
            branch: feature/multiboard
            board_id: 21
    runs-on: rpi-ros2-${{ matrix.ros_distribution }}-${{ matrix.board_id }}
    steps:
    # - uses: ros-tooling/setup-ros@0.2.1
    #   with:
    #     required-ros-distributions: ${{ matrix.ros_distribution }}
    - name: Create ROS 2 workspace
      run: |
        rm -rf ros_ws/src ros_ws/log
        mkdir -p ros_ws/src
    - uses: actions/checkout@v2
      with:
        path: ros_ws/src/micro_ros_renesas_testbench
        submodules: recursive
        ref: ${{ matrix.branch }}
    - name: Download dependencies
      run: |
        cd ros_ws
        vcs import --force --shallow --input src/micro_ros_renesas_testbench/requirements.repos src
    - name: Build micro-ROS library
      run: |
        bash ros_ws/src/micro_ros_renesas_testbench/test/micro_ros_renesas_testbench/scripts/build_microros.sh
    - name: Build and run tests
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.sh
        cd ros_ws
        source install/local_setup.bash
        colcon build --cmake-clean-cache --cmake-force-configure --packages-select micro_ros_renesas_testbench
        # colcon test --event-handlers console_direct+ --packages-select=micro_ros_renesas_testbench --return-code-on-test-failure --ctest-args -E "(cpplint)|(lint_cmake)|(uncrustify)|(xmllint)"
        RMW_IMPLEMENTATION=rmw_fastrtps_cpp ./build/micro_ros_renesas_testbench/micro_ros_renesas_testbench_test --gtest_filter=-HardwareTestMemoryProfiling*:*ThroughputTest*:*BenchmarkTestAllTransports*
    - name: Run profiling
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.sh
        cd ros_ws
        source install/local_setup.bash
        rm -rf *.txt
        RMW_IMPLEMENTATION=rmw_fastrtps_cpp ./build/micro_ros_renesas_testbench/micro_ros_renesas_testbench_test --gtest_filter=HardwareTestMemoryProfiling*:*ThroughputTest*:*BenchmarkTestAllTransports*
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: benchmark-results-${{ matrix.ros_distribution }}-${{ matrix.board_id }}
        path: ros_ws/*.txt