name: CI micro_ros_renesas_testbench

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron: '33 6 * * *'

jobs:
  micro_ros_renesas_testbench:
    runs-on: self-hosted
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ ubuntu-20.04 ]
    #     ros_distribution: [ rolling, galactic ]
    #     include:
    #       - docker_image: ubuntu:focal
    #         ros_distribution: rolling
    #       - docker_image: ubuntu:focal
    #         ros_distribution: galactic
    # container:
    #   image: ${{ matrix.docker_image }}
    steps:
    # - uses: ros-tooling/setup-ros@0.2.1
    #   with:
    #     required-ros-distributions: foxy
    - name: Create ROS 2 workspace
      run: |
        mkdir -p ros_ws/src
    - uses: actions/checkout@v2
      with:
        path: ros_ws/src/micro_ros_renesas_testbench
    - name: Install toolchain
      run: |
        cd ros_ws/src/micro_ros_renesas_testbench
        ./installtoolchain.sh
    - name: Download dependencies
      run: |
        cd ros_ws
        vcs import --input src/micro_ros_renesas_testbench/requirements.repos
    - name: Build
      run: |
        source /opt/ros/foxy/setup.sh
        cd ros_ws
        colcon build
