name: CI micro_ros_renesas_testbench

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron: '33 6 * * *'

jobs:
  micro_ros_renesas_testbench:
    runs-on: rpi-ros2-foxy
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [ foxy ]
    steps:
    # - uses: ros-tooling/setup-ros@0.2.1
    #   with:
    #     required-ros-distributions: ${{ matrix.ros_distribution }}
    - name: Create ROS 2 workspace
      run: |
        mkdir -p ros_ws/src
    - uses: actions/checkout@v2
      with:
        path: ros_ws/src/micro_ros_renesas_testbench
        submodules: recursive
        token: ${{ secrets.PRIVATE_KEY }}
    - name: Install toolchain
      run: |
        cd ros_ws/src/micro_ros_renesas_testbench
        ./installtoolchain.sh
    - name: Download dependencies
      run: |
        cd ros_ws
        vcs import --input src/micro_ros_renesas_testbench/requirements.repos src
    - name: Build micro-ROS library
      run: |
        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro_ros_renesas2estudio_component
          rm -rf libmicroros
        popd
        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro-ROS_tests
          mv makefile.init makefile.init.old || true
          make clean && make -j$(nproc)
        popd

        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_freeRTOS/micro_ros_renesas2estudio_component
          rm -rf libmicroros
        popd
        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_freeRTOS/micro-ROS_tests
          mv makefile.init makefile.init.old || true
          make clean && make -j$(nproc)
        popd

        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_threadX/micro_ros_renesas2estudio_component
          rm -rf libmicroros
        popd
        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_threadX/micro-ROS_tests
          mv makefile.init makefile.init.old || true
          make clean && make -j$(nproc)
        popd
    - name: Build tests
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.sh
        cd ros_ws
        colcon build --cmake-clean-cache --cmake-force-configure
