name: CI micro_ros_renesas_testbench

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron: '33 6 * * *'

jobs:
  micro_ros_renesas_testbench:
    runs-on: ubuntu-20.04
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ ubuntu-20.04 ]
    #     ros_distribution: [ rolling, galactic ]
    #     include:
    #       - docker_image: ubuntu:focal
    #         ros_distribution: rolling
    #       - docker_image: ubuntu:focal
    #         ros_distribution: galactic
    # container:
    #   image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v2
      with:
        path: checkout/
    - uses: ros-tooling/setup-ros@0.2.1
      with:
        required-ros-distributions: foxy
    - name: Build
      run: |
        sudo apt update
        echo hola
        echo $ROS_DISTRO
