name: CI galactic

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron: '33 6 * * *'

jobs:
  micro_ros_renesas_testbench:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [ galactic ]
    runs-on: rpi-ros2-${{ matrix.ros_distribution }}
    steps:
    # - uses: ros-tooling/setup-ros@0.2.1
    #   with:
    #     required-ros-distributions: ${{ matrix.ros_distribution }}
    - name: Create ROS 2 workspace
      run: |
        mkdir -p ros_ws/src
    - uses: actions/checkout@v2
      with:
        path: ros_ws/src/micro_ros_renesas_testbench
        submodules: recursive
        ref: ${{ matrix.ros_distribution }}
        token: ${{ secrets.PRIVATE_KEY }}
    - name: Download dependencies
      run: |
        cd ros_ws
        vcs import --input src/micro_ros_renesas_testbench/requirements.repos src
    - name: Build micro-ROS library
      run: |
        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro_ros_renesas2estudio_component
          rm -rf libmicroros
        popd
        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro-ROS_tests
          mv makefile.init makefile.init.old || true
          make clean && make -j$(nproc)
        popd

        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_freeRTOS/micro_ros_renesas2estudio_component
          rm -rf libmicroros
        popd

        # Copying library to speed up tests
        cp -r ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro_ros_renesas2estudio_component/libmicroros/ ros_ws/src/micro_ros_renesas_testbench/e2studio_project_freeRTOS/micro_ros_renesas2estudio_component/

        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_freeRTOS/micro-ROS_tests
          mv makefile.init makefile.init.old || true
          make clean && make -j$(nproc)
        popd

        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_threadX/micro_ros_renesas2estudio_component
          rm -rf libmicroros
        popd

        # Copying library to speed up tests
        cp -r ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro_ros_renesas2estudio_component/libmicroros/ ros_ws/src/micro_ros_renesas_testbench/e2studio_project_threadX/micro_ros_renesas2estudio_component/

        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_threadX/micro-ROS_tests
          mv makefile.init makefile.init.old || true
          make clean && make -j$(nproc)
        popd
    - name: Build micro-ROS agent
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.sh
        cd ros_ws
        colcon build --cmake-clean-cache --cmake-force-configure --packages-up-to micro_ros_agent
    - name: Build and run tests
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.sh
        cd ros_ws
        source install/local_setup.bash
        colcon build --cmake-clean-cache --cmake-force-configure --packages-select micro_ros_renesas_testbench
        # colcon test --event-handlers console_direct+ --packages-select=micro_ros_renesas_testbench --return-code-on-test-failure --ctest-args -E "(cpplint)|(lint_cmake)|(uncrustify)|(xmllint)"
        ./build/micro_ros_renesas_testbench/micro_ros_renesas_testbench_test